'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IncomingDetails

    '''<summary>
    '''LblPartNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPartNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblDataPartNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDataPartNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblSpec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSpec As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblDataSpec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDataSpec As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblDataName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDataName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblPONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPONo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataPO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblQty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblDataQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDataQty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblRequestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblRequestDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblDataRequestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDataRequestDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtNGQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNGQty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtWorkMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtWorkMin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtSide1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSide1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtSide2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSide2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtSide3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSide3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtSide4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSide4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtRejectRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRejectRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEdit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TxtTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTest As Global.System.Web.UI.WebControls.TextBox
End Class
