'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IncomingItems

    '''<summary>
    '''LnkRecieve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkRecieve As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LnkIncoming control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkIncoming As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LnkFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkFinish As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''PanelRecieve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelRecieve As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GrdRecieve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdRecieve As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PanelIncoming control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelIncoming As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GrdIncoming control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdIncoming As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PanelFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelFinish As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LblLotCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblLotCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMonth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GrdFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdFinish As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BtnDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDownload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnForJpn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnForJpn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TxtTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTest As Global.System.Web.UI.WebControls.TextBox
End Class
